stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE: registry.gitlab.com/store-builder

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t $DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA .
    - docker push $DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA

deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh
  script:
    - ssh user@your-server 'docker pull '$DOCKER_IMAGE':'$CI_COMMIT_SHORT_SHA' && docker stop app || true && docker rm app || true && docker run -d --name app -p 80:3000 '$DOCKER_IMAGE':'$CI_COMMIT_SHORT_SHA''
