name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  prepare:
    name: Set the Environment
    runs-on: ubuntu-24.04
    outputs:
      VERSION: ${{ steps.set-env.outputs.VERSION }}
      IMAGE_NAME: ${{ steps.set-env.outputs.IMAGE_NAME }}
      
    steps:
      - name: Compute version and image name
        id: set-env
        run: |
          VERSION="v${GITHUB_RUN_NUMBER}"
          OWNER=$(echo "${GITHUB_REPOSITORY_OWNER}" | tr '[:upper:]' '[:lower:]')
          IMAGE_NAME="ghcr.io/${OWNER}/application:${VERSION}"
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_OUTPUT
          
  build:
    name: Build & Upload Docker Image
    runs-on: ubuntu-24.04
    needs: prepare
    env:
      VERSION: ${{ needs.prepare.outputs.VERSION }}
      IMAGE_NAME: ${{ needs.prepare.outputs.IMAGE_NAME }}
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.WORKFLOW_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build docker image
        run: docker build -t $IMAGE_NAME .

      - name: Push the image into registry
        run: docker push $IMAGE_NAME

      - name: Make a new GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION }}
          name: "Release ${{ env.VERSION }}"
          body: "Automated release with Docker image `${{ env.IMAGE_NAME }}`"
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}

  deploy:
    name: Deploy on VPS
    runs-on: ubuntu-24.04
    needs: build
    env:
      IMAGE_NAME: ${{ needs.prepare.outputs.IMAGE_NAME }}

    steps:
      - name: Setup SSH
        run: mkdir -p ~/.ssh && echo "${{ secrets.SSH_PK }}" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa && ssh-keyscan -p ${{ secrets.SSH_PORT }} -H "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

      - name: Pull and deploy Docker image
        run: |
          IMAGE_NAME="${{ env.IMAGE_NAME }}"
          ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} '
            cd ./store-builder &&
            echo "${{ secrets.WORKFLOW_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin &&
            docker pull "${IMAGE_NAME}" &&
            docker tag "${IMAGE_NAME}" application &&
            docker compose down &&
            docker compose up -d'
