name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build & Upload Docker Image
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t application:latest .

      - name: Save image as tar file
        run: docker save application:latest -o application.tar

      - name: Setup SSH
        run: mkdir -p ~/.ssh && echo "${{ secrets.SSH_PK }}" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa && ssh-keyscan -H "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

      - name: Upload Docker image to VPS
        run: scp -C application.tar ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/tmp/application.tar

  deploy:
    name: Deploy on VPS
    runs-on: ubuntu-22.04
    needs: build

    steps:
      - name: Setup SSH
        run: mkdir -p ~/.ssh && echo "${{ secrets.SSH_PK }}" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa && ssh-keyscan -H "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

      - name: Load image and restart app
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "docker load -i ~/tmp/application.tar && rm ~/tmp/application.tar && cd ~/store-builder && docker compose down && docker compose up -d"
